cluster:
  children:
    server:
      hosts:
        olympus-hecate:
        olympus-phobos:
        olympus-zephyr:
    agent:
      hosts:
        olympus-uranus:
  vars:
    ansible_user: root
    # renovate: datasource=github-releases depName=k3s-io/k3s
    k3s_version: v1.33.1+k3s1
