cluster:
  children:
    server:
      hosts:
        olympus-hecate:
        olympus-phobos:
        olympus-zephyr:
    agent:
      hosts:
        olympus-uranus:
        atlas-ru:
          use_tailscale_ip: true
        # atlas-nl:
        #   use_tailscale_ip: true
  vars:
    ansible_user: root
    k3s_version: v1.32.3+k3s1
