- name: Install unattended-upgrades
  when: ansible_facts.get('distribution') == "Ubuntu"
  notify: Restart unattended-upgrades
  block:
    - name: Ensure unattended-upgrades is installed
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Configure 20auto-upgrades
      ansible.builtin.template:
        src: templates/20auto-upgrades.j2
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: "0644"

    - name: Configure 50unattended-upgrades
      ansible.builtin.template:
        src: templates/50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: "0644"
