- name: Restart hostname-dependent services
  become: true
  block:
    - name: Restart network service
      ansible.builtin.service:
        name: network
        state: restarted
      when: "'network' in ansible_facts.services"
      failed_when: ansible_facts.services['network'].state != "running"

    - name: Wait for the host to become available
      ansible.builtin.wait_for_connection:
        timeout: 300
